const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('file:///C:/LocalAI_Workstation/LexMind_Omni_計畫書_正式版.html', {waitUntil: 'networkidle0'});
  await page.pdf({ path: 'C:/Users/temp/Downloads/LexMind_Omni_計畫書_正式版.PDF', format: 'A4', margin: {top: '20px', bottom: '20px', left: '20px', right: '20px'} });
  await browser.close();
  console.log('PDF Generated by Puppeteer!');
})();
