import re
with open(r'C:\LocalAI_Workstation\app.py', 'r', encoding='utf-8-sig') as f:
    content = f.read()
content = re.sub(r'background-color:\s*#0b0f19\s*!important;', '/* removed */', content)
content = re.sub(r'color:\s*#ffffff\s*!important;', '/* removed */', content)
content = re.sub(r'background-color:\s*#111827\s*!important;', '/* removed */', content)
content = re.sub(r'border-right:\s*1px solid #1f2937\s*!important;', '/* removed */', content)
content = content.replace('background-color: #111827', 'background-color: #f9fafb')
content = content.replace('background-color:#111827', 'background-color:#f9fafb')
content = content.replace('background-color: #0b0f19', 'background-color: #ffffff')
content = content.replace('background-color:#0b0f19', 'background-color:#ffffff')
content = content.replace('background-color: #1e1b4b', 'background-color: #eff6ff')
content = content.replace('border: 1px solid #1f2937', 'border: 1px solid #e5e7eb')
content = content.replace('border:1px solid #1f2937', 'border:1px solid #e5e7eb')
content = content.replace('color: #ffffff', 'color: #1f2937')
content = content.replace('color:#ffffff', 'color:#1f2937')
content = content.replace('color: #e5e7eb', 'color: #374151')
content = content.replace('color: #9ca3af', 'color: #6b7280')
content = content.replace('color: #e0e7ff', 'color: #1e40af')
content = content.replace('h1, h2, h3, h4, h5, h6 { font-family: "Noto Serif TC", "PMingLiU", "MingLiU", serif !important; }', 'h1, h2, h3, h4, h5, h6 { color: #1A365D !important; font-family: "Noto Serif TC", "PMingLiU", "MingLiU", serif !important; }')
content = content.replace('div[data-baseweb="tab-list"] button { font-family: "Noto Serif TC", serif !important; font-size: 1.05em !important; }', 'div[data-baseweb="tab-list"] button { font-family: "Noto Serif TC", serif !important; font-size: 1.05em !important; color: #1F2937 !important; }')
content = content.replace('div[data-baseweb="tab-list"] button[aria-selected="true"] { color: #d97706 !important; font-weight: bold !important; border-bottom-color: #d97706 !important; }', 'div[data-baseweb="tab-list"] button[aria-selected="true"] { color: #1A365D !important; font-weight: bold !important; border-bottom-color: #1A365D !important; }')
content = content.replace('.stButton>button { background-color: #d97706 !important; color: white !important; border-radius: 4px !important; font-family: "Noto Serif TC", serif; }', '.stButton>button { background-color: #1A365D !important; color: white !important; border-radius: 4px !important; font-family: "Noto Serif TC", serif; }')
with open(r'C:\LocalAI_Workstation\app.py', 'w', encoding='utf-8-sig') as f:
    f.write(content)
print('Done')
